Repository redhat-developer/vscode-quarkus, pull requests merged in 2022-08, with the labels that each got.

#534 Update node to 14 in CI and CD
  .github/workflows/tests.yml
  Jenkinsfile
  package-lock.json
  package.json
Labels: build

#533 Clickable InlayHint for Java type
  src/qute/languageServer/inlayHintsProvider.ts
Labels: enhancement, qute

#538 Update Jenkinsfile to use Java 17.
  Jenkinsfile
  gulpfile.js
Labels: bug, build
