Repository redhat-developer/vscode-quarkus, pull requests merged in 2023-01, with the labels that each got.

#568 Fix GitHub Actions badge in README
  README.md
Labels: documentation

#570 Provide syntax coloration for #fragment
  language-support/qute/qute.tmLanguage.json
Labels: enhancement, qute, textmate

#571 Use the vsce in the `@vscode` namespace
  Jenkinsfile
  package-lock.json
Labels: build
