Repository redhat-developer/vscode-quarkus, pull requests merged in 2024-08, with the labels that each got.

#815 fix: set platformOnly to false to collect all extensions in the wizard
  src/utils/requestUtils.ts
Labels: enhancement

#711 Replace axios library with built-in fetch
  package-lock.json
  package.json
  src/utils/requestUtils.ts
Labels: debt

#817 Force language to 'quarkus-properties' doesn't work for application.properties
  src/extension.ts
Labels: bug

#816 Changelog for 0.18.0
  CHANGELOG.md
Labels: debt
